-- MySQL Script generated by MySQL Workbench
-- Tue Jan 23 20:10:29 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jurawallet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jurawallet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jurawallet` DEFAULT CHARACTER SET utf8mb4 ;
USE `jurawallet` ;

-- -----------------------------------------------------
-- Table `jurawallet`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jurawallet`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name_user` VARCHAR(50) NOT NULL,
  `lastname_user` VARCHAR(50) NOT NULL,
  `phonenumber_user` VARCHAR(15) NOT NULL,
  `email_user` VARCHAR(100) NOT NULL,
  `password_user` VARCHAR(255) NOT NULL,
  `birthday_user` DATE NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `jurawallet`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jurawallet`.`category` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `name_category` VARCHAR(50) NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_category`),
  INDEX `fk_category_user1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_category_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `jurawallet`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `jurawallet`.`typeOfTransaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jurawallet`.`typeOfTransaction` (
  `id_typeOfTransaction` INT NOT NULL AUTO_INCREMENT,
  `name_typeOfTransaction` VARCHAR(50) NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_typeOfTransaction`),
  INDEX `fk_typeOfTransaction_user1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_typeOfTransaction_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `jurawallet`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jurawallet`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jurawallet`.`transaction` (
  `id_transaction` INT NOT NULL AUTO_INCREMENT,
  `name_transaction` VARCHAR(255) NOT NULL,
  `price_transaction` DECIMAL(10,2) NOT NULL,
  `date_transaction` DATE NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `id_user` INT NOT NULL,
  `id_category` INT NOT NULL,
  `id_typeOfTransaction` INT NOT NULL,
  PRIMARY KEY (`id_transaction`),
  INDEX `id_user` (`id_user` ASC) VISIBLE,
  INDEX `fk_category_transaction` (`id_category` ASC) VISIBLE,
  INDEX `fk_transaction_typeOfTransaction1_idx` (`id_typeOfTransaction` ASC) VISIBLE,
  CONSTRAINT `fk_category_transaction`
    FOREIGN KEY (`id_category`)
    REFERENCES `jurawallet`.`category` (`id_category`),
  CONSTRAINT `transactions_ibfk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `jurawallet`.`user` (`id_user`),
  CONSTRAINT `fk_transaction_typeOfTransaction1`
    FOREIGN KEY (`id_typeOfTransaction`)
    REFERENCES `jurawallet`.`typeOfTransaction` (`id_typeOfTransaction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
